### ISSUE TITLE
No interior model after Sim Update 5

### ISSUE THREAD

**Issue by mdionizio** [Digital-Flight-Dynamics/DFD35X#17]
Virtual cockpit and interior model not available after the latest Sim Update.

**Comment by xZreai** [comment]
We will be updating it with time, at the moment it is not a huge priority since the actual aircraft is not out and we dont provide support for it either.

**Comment by mdionizio** [comment]
I'm not requesting support. I was merely pointing it out. In any case after a simple change to a parameter in the model.cfg file it is working as before.

**Comment by xZreai** [comment]
Yes you we're not requesting support for it, I know haha, and thanks for pointing it out. Could you point out which parameter it was in the model.cfg?

**Comment by mdionizio** [comment]
[model.options]
; if true, when showing the exterior, also show the interior model (default false)
withExterior_showInterior=false
; if true, when showing the interior with the exterior, exclude interior.lod.0 (default false); only has an effect when withExterior_showInterior is true
withExterior_showInterior_hideFirstLod=false
; when showing the interior, force showing lod0 (default true)
withInterior_forceFirstLod=false
; when showing the interior, also show the exterior model (default false)
withInterior_showExterior=**true**

**Comment by xZreai** [comment]
Thank you, and you can confirm this makes the model work as before?

**Comment by mdionizio** [comment]
Yes I can confirm that it worked at my end after I changed the parameter.

**Comment by xZreai** [comment]
Alright, thanks a lot!
